data_load:
  n_samples: 8
  noise_constant: 0.05
  x_lim:
  - 0
  - 1
  y_lim:
  - 0
  - 1.0
model_architecture:
  actfunc:
  - sigmoid
  batch_size: null
  layers:
  - 2
  - 5
  - 1
training:
  delta: 0.5
  delta_external: 0.0
  delta_synthetic: 0.0
  epsilon_synthetic: 0.0
  epsilon: 0.0
  learning_rate: 0.01
  monotone_relations:
  - 0
  - 1
  n_epochs: 5000
  patience: 100
  plot_history: True
  save_model: false
  std_growth: 0.0
  verbose: 1
  weight_decay: 0.2e-5
  seed: 0
  optimizer_type: 'LBFGS'