data_load:
  n_samples: 50
  noise_constant: 0.01
  x_lim:
  - -1
  - 1
  y_lim:
  - -1
  - 1
model_architecture:
  actfunc:
  - sigmoid
  batch_size: null
  layers:
  - 2
  - 3
  - 1
training:
  delta: 0.3
  delta_external: 0.0
  delta_synthetic: 0.0
  epsilon_synthetic: 0.0
  learning_rate: 0.01
  monotone_relations:
  - 1
  - 1
  n_epochs: 200
  patience: 500
  plot_history: true
  save_model: false
  std_growth: 0.0
  verbose: 1
  weight_decay: 1.0e-05
